#!/usr/bin/env python

Import("env")
Import("env_modules")

env_qurobullet = env_modules.Clone()

env_qurobullet.add_source_files(env.modules_sources, "*.cpp")
env_qurobullet.add_source_files(env.modules_sources, "resource/*.cpp")
